# Generated by Django 5.2.7 on 2025-10-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_location_event_locationn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='locationn',
            new_name='location',
        ),
    ]
